module.exports = {
  'clientId': '039c8da16d764b958b9da7a0bb1381b3',
  'clientSecret': '41769a9a05a7435ca81dd2831d933b5d',
  'attributes': {
    'track_mode_confidence': 'number',
    'track_key_confidence': 'number',
    'track_time_signature_confidence': 'number',
    'track_time_signature': 'number',
    'track_tempo_confidence': 'number',
    'track_end_of_fade_in': 'number',
    'duration_ms': 'number',
    'tempo': 'number',
    'valence': 'number',
    'liveness': 'number',
    'instrumentalness': 'number',
    'acousticness': 'number',
    'speechiness': 'number',
    'mode': 'number',
    'loudness': 'number',
    'key': 'number',
    'energy': 'number',
    'danceability': 'number',
  },
};
